accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
        path('', views.signup, name="signup"),
        path('login/', views.login, name="login"),
        path('logout/', views.logout, name="logout"),
        path('delete/', views.delete, name="delete"),
        path('update/', views.update, name="update"),
        path('password/', views.password, name="password"),
    ]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('<int:board_pk>/', views.detail, name="detail"),
    path('<int:board_pk>/delete/', views.delete, name="delete"),
    path('<int:board_pk>/edit/', views.edit, name="edit"),
    path('<int:board_pk>/userdetail/', views.userdetail, name="userdetail"),
]

django_fbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:user_pk>/', views.detail, name="detail"),
]

boards/models.py
from django.db import models
from django.urls import reverse
# from django.contrib.auth.models import User # 사용하지 마세요.
# from django.contrib.auth import get_user_model
from django.conf import settings
# settings.AUTH_USER_MODEL
# default 값이 'auth.User'

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    hit = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # CASCADE는 1:N을 묶어줌
    
    def __str__(self):
        return f'<Board ({self.id})> : {self.title}' 
        
    def get_absolute_url(self):
        return reverse('boards:detail', args=[self.pk])

boards/forms.py
from django import forms
from .models import Board
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# class BoardForm(forms.Form):
#     title = forms.CharField(label='제목', max_length=10, error_messages={'required': '제목을 반드시 입력해주세요.'})
#     content = forms.CharField(label='내용', error_messages={'required': '내용을 반드시 입력해주세요.'},
#                                             widget=forms.Textarea(attrs={'placeholder': '내용을 입력해줘!',
#                                                                          'class': 'input-box'
#                                             })

# modelform
class BoardForm(forms.ModelForm):                                      
    class Meta:
        model = Board
        fields = ['title', 'content']
        # fields = '__all__'
    #     widgets = {'title': forms.TextInput(attrs={
    #         'placeholder':'제목을 입력해주세요.', 'class': 'title'}),
    #               'content': forms.Textarea(attrs={
    #         'placeholder':'내용을 입력해주세요.', 'class': 'content'})
    #     }
    #     error_messages = {'title': {
    #         'required': '제목을 반드시 입력해주세요.'
    #     }, 'content': {
    #         'required': '내용을 반드시 입력해주세요.'
    #     }
    # }
    

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.form_method = 'POST'
    #     self.helper.add_input(Submit('submit', 'Submit'))
    

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Board
from .forms import BoardForm
import pprint, hashlib
from django.views.decorators.http import require_http_methods
# Create your views here.

def index(request):
    pprint.pprint(request.user)
    boards = Board.objects.order_by('-pk')
    context = {'boards': boards}
    return render(request, 'boards/index.html', context)

@login_required    
def create(request):
    if request.method == "POST":
        board_form = BoardForm(request.POST)
        if board_form.is_valid():
            # board = Board()
            # board.title = board_form.cleaned_data.get('title')
            # board.content = board_form.cleaned_data.get('content')
            # board.user = request.user
            # board.save()
            
            board = board_form.save(commit=False) # 돈을 보냈을 때 돈이 아직 들어오기전에는 틀만만들어두고 save하지 않는것
            board.user = request.user # 추가 작업을 해주고, 즉 commit=False 는 추가작업을 해주기 위한 것.
            board.save() # save를 해준다. 
            return redirect(board)
    else:
        board_form = BoardForm()
    context = {'board_form': board_form}
    return render(request, 'boards/form.html', context)

def detail(request, board_pk):
    # board = Board.objects.get(pk=board_pk)
    board = get_object_or_404(Board, pk=board_pk)
    board.hit += 1
    board.save()
    context = {'board': board}
    return render(request, 'boards/detail.html', context)
  
  
def userdetail(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    board.save()
    context = {'board': board}
    return render(request, 'boards/userdetail.html', context)
    
    
  
# @require_http_methods(["POST"])
def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    # board = Board.objects.get(pk=board_pk)
    if request.method == "POST":
        board.delete()
        return redirect('boards:index')
    else:
        if request.user != board.user:
            return redirect(board)
        return redirect(board)
        
# @require_http_methods(["POST"])
def edit(request, board_pk):
    # 1. board_pk에 해당하는 오브젝트르 가져온다.
    #    만약에 없으면 404 에러
    #    만약에 있으면 board = Board.objects.get(pk=board_pk)와 동일.
    board = get_object_or_404(Board, pk=board_pk)
    # 2-1. POST 요청이면 (사용자가 form을 통해 데이터를 보내준 것.)
    if request.method == "POST":
        
        # 사용자 입력값(request.POST)을 BoardForm에 전달해주고, 
        board_form = BoardForm(request.POST, instance=board)
        
        # 검증 (유효성 체크)
        if board_form.is_valid():
            # board.title = board_form.cleaned_data.get('title')
            # board.content = board_form.cleaned_data.get('content')
            # board.save()
            board = board_form.save()
            return redirect(board)
    # 2-2: GET 요청이면 (수정하기 버튼을 눌렀을 때)
    else:
        # if request.user != board.user:
            # return redirect(board)
        # BoardForm을 초기화(사용자 입력값을 넣어준 상태)
        # board_form = BoardForm(initial=board.__dict__) 이렇게 작성해도 가능
        board_form = BoardForm(instance=board)
    # context에 담겨 있는 board_form은 아래와 같이 가능함.
    # 1 - POST 요청에서 검증에 실패하였을 때, 오류 메시지가 포함된 상태
    # 2 - GET 요청에서 초기화된 상태
    context = {'board_form': board_form}
    return render(request, 'boards/form.html', context)
    

boards/templates/boards/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FBV</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
    form {
        display: inline;
    }
    
</style>
</head>
<body>
    {% if messages %}
    <!--<ul class="messages">-->
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}" role="alert"{% endif %}>{{ message }}</div>
        {% endfor %}
    <!--</ul>-->
    {% endif %}
    {% if user.is_authenticated %}
    
    <nav class="navbar navbar-expand-lg navbar-light" style = "background-color: lightblue">
        <a class="navbar-brand" href="{% url 'boards:index' %}">싸피인사이드</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:update' %}">프로필 수정</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:detail' user.pk %}">마이 페이지</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href ="{% url 'users:index' %}">이용하는 유저</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href ="{% url 'boards:index' %}">자유 게시판</a>
              </li>
              
            </ul>
        </div>
    </nav>
    
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-light" style = "background-color: lightblue">
        <a class="navbar-brand" href="{% url 'boards:index' %}">싸피인사이드</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
              </li>
            </ul>
        </div>
    </nav>
    {% endif %}
    
    
    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
</body>
</html>

boards/templates/boards/create.html
{% extends 'boards/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ board_form.as_p }}
    <!--<input type="text" name="title">-->
    <!--<textarea name="content"></textarea>-->
    <input type="submit">
</form>


{% endblock %}

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
<h1>{{ board.pk }}번째 글</h1>
<h2>제목 : {{ board.title }}</h2>
<h3>작성자 : {{ board.user.username }}</h3>
<p>조회수 : {{ board.hit }}</p>
<hr>
<p>{{ board.content }}</p>

{% if request.user.is_superuser %}
   <form action="{% url 'boards:delete' board.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    
    <a href= "{% url 'boards:edit' board.pk %}"><input type="submit" value="수정"></a>

{% elif request.user == board.user %}
    <form action="{% url 'boards:delete' board.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    
    <a href= "{% url 'boards:edit' board.pk %}"><input type="submit" value="수정"></a>
    <br>
{% endif %}
<br>

<!--<a href= "{% url 'users:detail' user.pk %}"><input type="submit" value="해당 유저 프로필 가기"></a>-->
{% endblock %}

boards/templates/boards/form.html
{% extends 'boards/base.html' %}

{% block body %}
{% load crispy_forms_tags %}
{% if request.resolver_match.url_name == 'create' %}
    <h1>글 생성</h1>
{% else %}
    <h1>글 수정</h1>
{% endif %}

<!--{% crispy board_form %}-->
<form method="POST">
    {% csrf_token %}
    {{ board_form|crispy }}
    <input type="submit">
</form>


{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block body %}
<hr>
<a href = "{% url 'users:index' %}"> 유저 목록 보러가기 </a>
<br>
<br>

<h1>게시글 목록</h1>
{% if user.is_authenticated %}
    <a href= "{% url 'boards:create' %}">글 쓰러가기</a>
<hr>
{% endif %}
{% for board in boards %}
    <p>id : {{ board.pk }}</p>
    <p>닉네임 : {{ board.user }}</p>
    <p>제목 : {{ board.title }}</p>
    <a href="{% url 'boards:detail' board.pk %}">글 보러가기</a>
    <hr>
{% endfor %}

{% endblock %}