accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
        path('', views.signup, name="signup"),
        path('login/', views.login, name="login"),
        path('logout/', views.logout, name="logout"),
        path('delete/', views.delete, name="delete"),
        path('update/', views.update, name="update"),
        path('password/', views.password, name="password"),
    ]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('<int:board_pk>/', views.detail, name="detail"),
    path('<int:board_pk>/delete/', views.delete, name="delete"),
    path('<int:board_pk>/edit/', views.edit, name="edit"),
    path('<int:board_pk>/userdetail/', views.userdetail, name="userdetail"),
]

django_fbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:user_pk>/', views.detail, name="detail"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User

def index(request):
    User = get_user_model()
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'users/index.html', context)

def detail(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    # board 는 유저를 1개만 갖고 있으므로 boards.user 이고 user는 여러개의 board를 갖고있으므로
    boards = user.board_set.all()
    context = {'user_detail': user, 'boards': boards}
    return render(request, 'users/detail.html', context)

users/templates/users/detail.html
{% extends 'boards/base.html' %}
{% block body %}

{% load gravatar %}
<img src="https://s.gravatar.com/avatar/{{ user_detail.email|makehash }}?s=150&d=">
<h2>이메일 : {{ user_detail.email }}</h2>
<br>
<h2>닉네임 : {{ user_detail.username }}</h2>
<br>
<h1> 쓴 글 목록 </h1>
{% for board in boards %}
<a href="{% url 'boards:detail' board.pk %}">{{ board.title }}</a>
<br>
{% endfor %}
<br>
<br>


<form action="{% url 'accounts:delete' %}" method = "POST">
    {% csrf_token %}
    <input type="submit" value= "회원탈퇴">
</form>

{% endblock %}

users/templates/users/index.html
{% extends 'boards/base.html' %}
{% block body %}
<a href = "{% url 'boards:index' %}">게시판 가기</a>
<br>
<br>
<h1> 유저 목록 </h1>
{% for user in users %}
    <a>{{ user.username }}</a> &nbsp;/ &nbsp; <a>{{ user.pk }}</a> 
    <br>
    <a href = "{% url 'users:detail' user.pk %}"> 프로필 보러가기</a>
    
    <br>
    <br>
{% endfor %}

{% endblock %}